# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/clean/42_transformer.ipynb.

# %% auto 0
__all__ = ['model_iter']

# %% ../nbs/clean/42_transformer.ipynb 17
from IPython.core.debugger import set_trace

def _model_iter(ms):
    set_trace()
    if len(ms) == 0:
        return 
    m, *rest = ms    
    children = list(m.children())
    if len(children) == 0:
        yield m
        
    rest = children + rest
    yield from _model_iter(rest)

def model_iter(m):
    return _model_iter([m])
